import { invalid } from '@openape/report-contracts/html'

export type PlanLanguage = 'en' | 'de'
const german: Record<string, string> = {
  'Implementation plan': 'Umsetzungsplan',
  'Status': 'Status',
  'Proposal revision': 'Planrevision',
  'Owner approval: not recorded': 'Freigabe: nicht dokumentiert',
  'Decision recorded · approval target unverified': 'Entscheidung dokumentiert · Freigabebezug ungeprüft',
  'Other proposal revision approved · current revision not covered': 'Andere Planrevision freigegeben · aktuelle Revision nicht abgedeckt',
  'Decision recorded for a referenced artifact · current-source equivalence unverified': 'Entscheidung für referenziertes Dokument dokumentiert · Übereinstimmung mit aktuellem Plan ungeprüft',
  'Approval recorded for this proposal revision': 'Freigabe für diese Planrevision dokumentiert',
  'A lifecycle status does not grant approval.': 'Ein Bearbeitungsstatus stellt keine Freigabe dar.',
  'Approval scope (original wording)': 'Umfang der Freigabe (Originalwortlaut)',
  'Decision reference (original wording)': 'Entscheidungsbezug (Originalwortlaut)',
  'Approved proposal revision': 'Freigegebene Planrevision',
  'Referenced artifact': 'Referenziertes Dokument',
  'Recorded source SHA-256': 'Dokumentierte Quell-Prüfsumme (SHA-256)',
  'Original approval statement': 'Freigabe im Originalwortlaut',
  'Context & problem': 'Hintergrund und Problem',
  'Scope': 'Umfang',
  'Included': 'Enthalten',
  'Out of scope': 'Nicht enthalten',
  'Decisions': 'Entscheidungen',
  'Milestones': 'Meilensteine',
  'complete': 'abgeschlossen',
  'of': 'von',
  'Accepted when': 'Erfüllt, wenn',
  'Blocker': 'Hindernis',
  'Evidence': 'Nachweis',
  'Rollback': 'Rücknahme',
  'Completion outcome': 'Ergebnis des Abschlusses',
  'Not assessed. Completed work does not imply an achieved outcome.': 'Nicht bewertet. Abgeschlossene Arbeit bedeutet nicht automatisch, dass das Ziel erreicht wurde.',
  'Risks & tradeoffs': 'Risiken und Abwägungen',
  'Rollback summary': 'Rücknahme im Überblick',
  'Not recorded': 'Nicht dokumentiert',
  'Verification': 'Überprüfung',
  'Handoff & next action': 'Übergabe und nächster Schritt',
  'Changelog': 'Änderungsverlauf',
  'Problem at a glance': 'Das Problem auf einen Blick',
  'Problem': 'Problem',
  'Impact': 'Auswirkung',
  'Approach': 'Ansatz',
  'Outcome': 'Ziel',
  'draft': 'Entwurf', 'active': 'In Arbeit', 'paused': 'Pausiert', 'done': 'Abgeschlossen', 'archived': 'Archiviert',
  'planned': 'Geplant', 'blocked': 'Blockiert',
  'proposed': 'Vorgeschlagen', 'accepted': 'Angenommen', 'rejected': 'Abgelehnt', 'superseded': 'Ersetzt',
  'achieved': 'Erreicht', 'partial': 'Teilweise erreicht', 'not-achieved': 'Nicht erreicht', 'not-assessed': 'Nicht bewertet',
  'Content and inspection attestations are supplied by the author. The renderer does not execute checks or verify the author\'s identity.': 'Inhalte und Prüfbestätigungen stammen vom Autor. Der Renderer führt keine Tests aus und überprüft die Identität des Autors nicht.',
}
export function planLabel(language: PlanLanguage, value: string): string {
  if (language === 'en') return value
  return german[value] ?? invalid(`Missing German template label: ${value}`)
}
