export { loadAdapter, resolveAdapterPath, tryLoadAdapter } from './adapters.js'
export { appendAuditLog, type AuditEntry } from './audit.js'
export { extractShellCommandString, loadOrInstallAdapter, parseShellCommand, type ParsedShellCommand } from './shell-parser.js'
export { resolveCapabilityRequest } from './capabilities.js'
export { extractOption, extractWrappedCommand } from './commands/explain.js'
export { createShapesGrant, executeResolvedViaExec, fetchGrantToken, findExistingGrant, resolveFromGrant, verifyAndConsume, verifyAndExecute, waitForGrantStatus } from './grants.js'
export { resolveCommand } from './parser.js'
export { buildExactCommandGrantRequest, buildStructuredCliGrantRequest } from './request-builders.js'
export { fetchRegistry, findAdapter, searchAdapters } from './registry.js'
export { findConflictingAdapters, getInstalledDigest, installAdapter, isInstalled, removeAdapter } from './installer.js'
export type { AdapterMeta, BuiltGrantRequest, GrantRequestOptions, LoadedAdapter, RegistryEntry, RegistryIndex, ResolvedCapability, ResolvedCommand, ShapesAdapter, ShapesOperation } from './types.js'
