import { homedir } from 'node:os'
import { join } from 'node:path'

/**
 * Default audit-log path. Follows the XDG Base Directory spec for state files
 * (transient, machine-local, not config). Falls back to `~/.local/state` when
 * `$XDG_STATE_HOME` is unset.
 */
function defaultAuditPath(): string {
  const xdg = process.env.XDG_STATE_HOME
  const stateDir = xdg && xdg.length > 0 ? xdg : join(homedir(), '.local', 'state')
  return join(stateDir, 'openape', 'proxy-audit.jsonl')
}

export interface ProxyConfigOptions {
  /**
   * The agent's email (sub-claim of their IdP token). Used as `requester` in
   *  grant requests so IdP-side YOLO/allow/deny lookups key on the real user.
   */
  agentEmail: string
  /** IdP base URL the proxy talks to for grant approval + JWKS verify. */
  idpUrl: string
  /**
   * `true` (M3 default when logged in): every unmatched egress goes through an
   *  IdP grant request → user's YOLO policy (audience='ape-proxy') applies.
   * `false` (fallback when not logged in): default-allow + local deny-list +
   *  audit-log only. No IdP roundtrip. Honest about the trade-off.
   */
  mediated: boolean
}

/**
 * Build a default TOML config for the ephemeral proxy spawned by `apes proxy --`.
 *
 * Two modes:
 *
 * - **Mediated (`mediated=true`)**: `default_action="request"` so every
 *   unmatched host hits the IdP grant flow. The user's YOLO policy on
 *   `id.openape.ai/agents/<email>` (Web tab) decides auto-approve vs human.
 *   This is the M3 mode and what `apes proxy --` does when the caller is
 *   logged in via `apes login`.
 *
 * - **Transparent (`mediated=false`)**: legacy M1a behaviour — `default_action
 *   ="allow"` plus the cloud-metadata deny-list, no IdP roundtrip. Used when
 *   the caller isn't logged in (we can't synthesize an identity for grant
 *   lookups, so falling back to permissive-with-audit is the honest default
 *   instead of locking everything down).
 */
export function buildDefaultProxyConfigToml(opts: ProxyConfigOptions): string {
  const auditPath = defaultAuditPath()
  const defaultAction = opts.mediated ? 'request' : 'allow'
  const escEmail = opts.agentEmail.replace(/"/g, '\\"')
  const escIdp = opts.idpUrl.replace(/"/g, '\\"')
  return `# Auto-generated by \`apes proxy --\`. Do not edit; this file is
# recreated for every invocation and deleted on exit.
# Mode: ${opts.mediated ? 'IdP-mediated (every unmatched host → grant flow)' : 'transparent (default-allow + audit-only)'}.
[proxy]
listen = "127.0.0.1:0"
idp_url = "${escIdp}"
agent_email = "${escEmail}"
default_action = "${defaultAction}"
audit_log = "${auditPath.replace(/"/g, '\\"')}"

# Cloud / link-local metadata endpoints — never let agent traffic reach these
# even if a downstream policy mistake would otherwise allow it.
[[deny]]
domain = "169.254.169.254"
note = "AWS / DigitalOcean / Azure metadata endpoint"

[[deny]]
domain = "metadata.google.internal"
note = "GCP metadata endpoint"

[[deny]]
domain = "*.internal"
note = "VPC-internal hostname suffix"
`
}
