import { homedir } from 'node:os'
import { join } from 'node:path'

/**
 * Default audit-log path. Follows the XDG Base Directory spec for state files
 * (transient, machine-local, not config). Falls back to `~/.local/state` when
 * `$XDG_STATE_HOME` is unset.
 */
function defaultAuditPath(): string {
  const xdg = process.env.XDG_STATE_HOME
  const stateDir = xdg && xdg.length > 0 ? xdg : join(homedir(), '.local', 'state')
  return join(stateDir, 'openape', 'proxy-audit.jsonl')
}

/**
 * Build a minimal default TOML config for the ephemeral proxy spawned by
 * `apes proxy --`. M1a defaults are intentionally permissive — `default_action
 * = "allow"` plus a small deny-list for cloud-metadata IPs. The hardening
 * (mandatory_auth, grant_required) lands in M3.
 *
 * The returned string is dropped into a tmpfile for the proxy's `-c` flag.
 */
export function buildDefaultProxyConfigToml(): string {
  const auditPath = defaultAuditPath()
  return `# Auto-generated by apes proxy -- (M1a). Do not edit; this file is
# recreated for every \`apes proxy --\` invocation and deleted on exit.
[proxy]
listen = "127.0.0.1:0"
idp_url = "https://id.openape.ai"
agent_email = "ephemeral@apes-proxy.local"
default_action = "allow"
audit_log = "${auditPath.replace(/"/g, '\\"')}"

# Cloud / link-local metadata endpoints — never let agent traffic reach these
# even if a downstream policy mistake would otherwise allow it.
[[deny]]
domain = "169.254.169.254"
note = "AWS / DigitalOcean / Azure metadata endpoint"

[[deny]]
domain = "metadata.google.internal"
note = "GCP metadata endpoint"

[[deny]]
domain = "*.internal"
note = "VPC-internal hostname suffix"
`
}
