export const programHelp = {
  purpose: 'Assignment, command permission, network access and authentication are separate. A host CLI or host login does not make it available to a Pod.',
  steps: [
    'Call list, select and resources list. Find the installed executable on the Mac and inspect its Shapes adapter. Never guess a path, command, extension or login status.',
    'Assign the executable with program add: outer revision, path, optional adapterPath/commandName/runtimePath, and command {type:"add",podId,epoch}. Reuse an existing assignment. To change its executable or adapter use replace with applicationId and current epoch; this resets command grants.',
    'Inspect the returned application command reference. program prepare with command {type:"prepare",podId,line:"az --help"} lists adapter operations; an exact command line returns applicationId, argv, epoch, permission and needsGrant without executing it. This resolves the adapter only; it does not prove that the executable, interpreter or provider works.',
    'Grant each required command with program grant {podId,applicationId,epoch,argv}, where argv excludes the executable. Configure program network {podId,applicationId,epoch,hosts} with the actual HTTPS hostnames needed by the CLI. Use fresh resource epochs after every change.',
    'Before asking for login, ensure the adapter includes the exact authentication command as well as required read commands. Open the Pod terminal from Permissions. Exit and reopen an already-open terminal after assignments change: its PATH contains only the applications assigned when it opened. Use help there to see available applications.',
    'The owner authenticates inside that Pod terminal. It uses private application state, not the owner home or host login. Finish with exit and wait for successful state saving before running the Pod. Closing the window or a failed session does not save login changes. Never copy owner login stores, expose tokens, or send terminal output through MCP.',
    'Check required interpreters and extensions separately. In particular, Homebrew az uses Python and Azure DevOps commands need the azure-devops extension. An extension installed in the owner home is not installed in the Pod. The encrypted application state supports at most 4 MB and 128 files; do not install extension code into it. Terminal success does not certify a script sandbox execution.',
    'Save the script with the exact assigned tool capability and context.tools.invoke({application:assignedName,argv:[...]}); scripts allow granted read/list/get operations only. Validate, then perform the requested live check and inspect its state. Missing runtime dependencies, login or provider access remain incomplete setup even if synthetic validation succeeds.',
  ],
  runtimeDescriptor: {
    input: 'For an interpreted CLI, pass runtimePath to program add/replace. It is an owner-controlled JSON file up to 64 KB: {version:1,executable:"/absolute/interpreter",arguments:["fixed","arguments"],readDirectories:["/specific/package"],environment:{NON_SECRET_SETTING:"value"}}. Paths must exist. Use a native interpreter binary, not another launcher that spawns a child. Read-only package directories may contain code, libraries and extensions, never credentials.',
    integrity: 'The interpreter and descriptor are hash-checked before use. Changing either requires replacing the assignment and renewing command grants. Replacement preserves private login state. Terminal and script invocation use the same interpreter, fixed arguments and environment. Owner HOME/PATH, loader overrides, credentials and proxy overrides are not runtime settings.',
    azure: 'Homebrew az needs its native Python.app executable plus the Azure site-packages and exact dependency keg directories. Its bin/python stub spawns a child and is not the native interpreter. Install the official azure-devops extension in a separate code directory, set AZURE_EXTENSION_DIR to that directory, and include it among runtime readDirectories. Never install extension code in encrypted application state. Inspect the actual installation paths and verify az version plus az repos pr list --help in an empty-HOME sandbox before changing a real Pod.',
  },
  secrets: 'All ready secrets assigned to this Pod are available through context.credentials.get(alias). No credential.* declaration, checkbox selection or approveCredentials call is needed. Missing or revoked aliases fail when read. Values are never returned to Codex.',
  troubleshooting: {
    commandNotFound: 'Check the Pod assignment and reopen its terminal. Do not add the owner PATH or home to work around a missing assignment.',
    noAdapterOperation: 'Inspect and correct the adapter for the exact command, replace the assignment and restore required grants. Authentication commands belong to the owner terminal, not a scheduled script.',
    login: 'A host login is not evidence of Pod authentication. Complete the provider login in the Pod terminal, exit successfully, then verify the intended read.',
    execution: 'A resolved permission or synthetic validation does not prove an interpreter/extension can execute in the native sandbox. Report the actual missing dependency and complete runtime support before enabling a schedule.',
  },
}
