// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-01-01',
  devtools: { enabled: true },

  modules: ['@nuxt/ui', '@openape/nuxt-auth-sp'],

  app: {
    head: {
      link: [
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
        { rel: 'manifest', href: '/manifest.webmanifest' },
        // iOS Safari ignores SVG apple-touch-icons; PNG is required for
        // installed home-screen icons. Generated by scripts/generate-icons.sh.
        { rel: 'apple-touch-icon', href: '/icon-192.png', sizes: '192x192' },
        { rel: 'apple-touch-icon', href: '/icon-512.png', sizes: '512x512' },
      ],
    },
  },

  css: ['~/assets/main.css'],

  runtimeConfig: {
    // DB — overridden at runtime by NUXT_TURSO_URL. Defaults to a local dev
    // file so `pnpm dev` works without any env setup. Production MUST set
    // NUXT_TURSO_URL (path under shared/ so it survives deploy rotation).
    tursoUrl: 'file:./dev.db',
    tursoAuthToken: '',
    // Invite JWT — runtime-overridden by NUXT_INVITE_SECRET.
    inviteSecret: 'dev-invite-secret-change-me-min-32-chars',
    // CLI token JWT (HS256) now uses openapeSp.sessionSecret as the signing
    // secret (via signTimerackCliToken / verifyTimerackCliToken). The old
    // cliTokenSecret / idpIssuer / idpJwksUri / idpAudience keys have been
    // removed — DDISA issuer resolution is handled by the shared
    // resolveIssuerForToken auto-imported from @openape/nuxt-auth-sp.
    // NUXT_PUBLIC_URL — canonical public origin (deep-links, redirects).
    publicUrl: 'https://timetrack.openape.ai',
    public: {
      siteName: 'OpenApe Timetrack',
    },
  },

  colorMode: {
    preference: 'dark',
    fallback: 'dark',
  },

  openapeSp: {
    clientId: process.env.NUXT_OPENAPE_CLIENT_ID || 'timetrack.openape.ai',
    spName: 'OpenApe Timetrack',
    // Canonical env: NUXT_OPENAPE_SP_SESSION_SECRET. NUXT_SESSION_SECRET is
    // kept as a legacy fallback for existing prod .env files — remove after
    // all deploys have been rotated.
    sessionSecret: process.env.NUXT_OPENAPE_SP_SESSION_SECRET
      || process.env.NUXT_SESSION_SECRET
      || 'dev-session-secret-at-least-32-characters-long',
    fallbackIdpUrl: process.env.NUXT_FALLBACK_IDP_URL || 'https://id.openape.ai',
    // Scope catalog — discoverable at /.well-known/openape.json (protocol
    // sp-data-access.md §3). A Receiver requests a subset of these.
    manifest: {
      scopes: [
        {
          id: 'timetrack:read',
          description: 'Read your time entries, companies, projects and reports.',
          grants: ['GET /api/me/entries', 'GET /api/companies', 'GET /api/projects', 'GET /api/report'],
        },
        {
          id: 'timetrack:write',
          description: 'Create, edit and delete your time entries.',
          grants: ['POST /api/entries', 'PATCH /api/entries/:id', 'DELETE /api/entries/:id'],
        },
        {
          id: 'timetrack:report',
          description: 'Read aggregated time reports (totals, billable, breaks).',
          grants: ['GET /api/report'],
        },
      ],
    },
  },

  nitro: {
    preset: 'node-server',
    // PFLICHT: ohne asyncContext fällt useEvent()/Store-Lookup in Nitro
    // still auf Defaults zurück (leere Daten). Siehe OpenApe Memory-Lesson.
    experimental: { asyncContext: true },
  },
})
