const e2e = process.env.OPENAPE_E2E === '1'
const localIssuer = process.env.OPENAPE_ISSUER || 'https://id.openape.ai'

export default defineNuxtConfig({
  future: { compatibilityVersion: 4 },
  nitro: { experimental: { asyncContext: true } },
  modules: ['@nuxt/ui', '@openape/nuxt-auth-idp', '@sentry/nuxt/module', '@vite-pwa/nuxt'],
  css: ['~/assets/css/main.css'],
  colorMode: { preference: 'dark' },

  app: {
    head: {
      link: [
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
        // iOS Safari ignores SVG apple-touch-icons silently and falls back
        // to a screenshot of the page; PNGs are required for installed PWA
        // home-screen icons. Generated by scripts/generate-idp-icons.sh.
        { rel: 'apple-touch-icon', href: '/icon-192.png', sizes: '192x192' },
        { rel: 'apple-touch-icon', href: '/icon-512.png', sizes: '512x512' },
      ],
      meta: [
        { name: 'theme-color', content: '#18181b' },
        { name: 'description', content: 'OpenApe Identity Provider — passkeys, agents, grants.' },
        { name: 'apple-mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent' },
        { name: 'apple-mobile-web-app-title', content: 'OpenApe IdP' },
        { property: 'og:type', content: 'website' },
        { property: 'og:site_name', content: 'OpenApe ID' },
        { property: 'og:title', content: 'OpenApe ID — passwordless authentication with passkeys' },
        { property: 'og:description', content: 'Free DDISA Identity Provider for domains without their own IdP.' },
        { property: 'og:url', content: 'https://id.openape.ai' },
        { property: 'og:image', content: 'https://id.openape.ai/og-image.png' },
        { property: 'og:image:width', content: '1200' },
        { property: 'og:image:height', content: '630' },
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:title', content: 'OpenApe ID — passwordless with passkeys' },
        { name: 'twitter:description', content: 'Free DDISA Identity Provider.' },
        { name: 'twitter:image', content: 'https://id.openape.ai/og-image.png' },
      ],
    },
  },

  openapeIdp: {
    sessionSecret: process.env.OPENAPE_SESSION_SECRET || '',
    managementToken: process.env.OPENAPE_MANAGEMENT_TOKEN || '',
    adminEmails: process.env.OPENAPE_ADMIN_EMAILS || '',
    storageKey: 'idp',
    issuer: localIssuer,
    rpName: process.env.OPENAPE_RP_NAME || 'OpenApe Free IdP',
    rpID: process.env.OPENAPE_RP_ID || new URL(localIssuer).hostname,
    rpOrigin: process.env.OPENAPE_RP_ORIGIN || localIssuer,
    rpHostAllowList: process.env.OPENAPE_RP_HOST_ALLOWLIST || 'id.openape.ai,id.openape.at',
    grants: { enablePages: true, storageKey: 'grants' },
    routes: { admin: e2e },
  },

  runtimeConfig: {
    resendApiKey: '',
    resendFrom: 'auth@openape.ai',
    tursoUrl: '',
    tursoAuthToken: '',
    // VAPID keypair for grant-approval push notifications. Generate once
    // with `scripts/generate-idp-vapid.sh` and persist to env. The public
    // key is sent to clients (PushManager.subscribe needs it); private key
    // and subject (a mailto: that push services can use to contact us if
    // we misbehave) are server-side only. Defaults to empty so dev still
    // boots without push — the helper silently no-ops in that case.
    vapidPrivateKey: process.env.NUXT_VAPID_PRIVATE_KEY || '',
    vapidSubject: process.env.NUXT_VAPID_SUBJECT || 'mailto:patrick@hofmann.eco',
    public: {
      maxAgentsPerUser: Number(process.env.NUXT_PUBLIC_MAX_AGENTS_PER_USER || 100),
      vapidPublicKey: process.env.NUXT_PUBLIC_VAPID_PUBLIC_KEY || '',
    },
  },

  // PWA + custom service worker. injectManifest mode lets us own sw.ts so
  // we can register `push` and `notificationclick` handlers (vite-pwa's
  // generateSW mode can't expose those). srcDir: '..' resolves to the
  // Nuxt project root (apps/openape-free-idp/sw.ts) — see the chat app's
  // PR #203 for why the file lives outside app/ rather than under it.
  pwa: {
    strategies: 'injectManifest',
    srcDir: '..',
    filename: 'sw.ts',
    registerType: 'autoUpdate',
    manifest: {
      name: 'OpenApe IdP',
      short_name: 'OpenApe IdP',
      description: 'Passkeys, agents, and grant approval — for the open web.',
      theme_color: '#18181b',
      background_color: '#18181b',
      display: 'standalone',
      start_url: '/',
      scope: '/',
      icons: [
        { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
        { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
        { src: '/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        { src: '/icon.svg', sizes: 'any', type: 'image/svg+xml' },
      ],
    },
    injectManifest: {
      globPatterns: ['**/*.{js,css,html,ico,png,svg,webmanifest}'],
    },
    client: {
      installPrompt: true,
      periodicSyncForUpdates: 60 * 60,
    },
    devOptions: {
      enabled: false, // SW + HMR is a debugging nightmare in dev
    },
  },

  compatibilityDate: '2025-01-01',
})
