// Helpers for `apes agents spawn --bridge`. The chat-bridge is a daemon
// that runs as the agent user, listens to chat.openape.ai, and forwards
// messages to a local LLM CLI (default: pi). It needs access to a local
// litellm proxy — which is set up out-of-band by the spawning user (today:
// hand-crafted at ~/litellm/.env; tomorrow: managed by `apes agents llm
// setup` if we ever build that).

import { existsSync, readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

export const BRIDGE_PLIST_LABEL = 'eco.hofmann.apes.bridge'

export interface BridgeConfig {
  /** Where the bridge will POST messages — http://host:port/v1 */
  baseUrl: string
  /** Master key for the litellm proxy */
  apiKey: string
}

/**
 * Read defaults from `~/litellm/.env` (the hand-crafted location patrick
 * uses today). Returns null if no file or no key found.
 */
export function readLitellmEnv(envPath: string = join(homedir(), 'litellm', '.env')): { apiKey?: string, baseUrl?: string } | null {
  if (!existsSync(envPath)) return null
  try {
    const text = readFileSync(envPath, 'utf8')
    const out: { apiKey?: string, baseUrl?: string } = {}
    for (const line of text.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const eq = trimmed.indexOf('=')
      if (eq < 0) continue
      const key = trimmed.slice(0, eq).trim()
      const value = trimmed.slice(eq + 1).trim()
      if (key === 'LITELLM_MASTER_KEY' || key === 'LITELLM_API_KEY') out.apiKey = value
      if (key === 'LITELLM_BASE_URL') out.baseUrl = value
    }
    return out
  }
  catch {
    return null
  }
}

/**
 * Resolve the bridge config from CLI flags + ~/litellm/.env defaults.
 * CLI flags win over the file. Throws if no apiKey can be resolved.
 */
export function resolveBridgeConfig(opts: {
  cliKey?: string
  cliBaseUrl?: string
  envPath?: string
}): BridgeConfig {
  const env = readLitellmEnv(opts.envPath)
  const apiKey = opts.cliKey ?? env?.apiKey
  const baseUrl = opts.cliBaseUrl ?? env?.baseUrl ?? 'http://127.0.0.1:4000/v1'
  if (!apiKey) {
    throw new Error(
      'No LITELLM_API_KEY resolved. Pass --bridge-key sk-… or write LITELLM_MASTER_KEY into ~/litellm/.env first.',
    )
  }
  return { baseUrl, apiKey }
}

export function buildBridgeEnvFile(cfg: BridgeConfig): string {
  return `# Auto-generated by 'apes agents spawn --bridge'.
# Read by the chat-bridge daemon at boot to talk to the local LLM proxy.
LITELLM_BASE_URL=${cfg.baseUrl}
LITELLM_API_KEY=${cfg.apiKey}
`
}

/** Lives at `$HOME/Library/Application Support/openape/bridge/start.sh`. */
export function buildBridgeStartScript(): string {
  return `#!/usr/bin/env bash
# Auto-generated by 'apes agents spawn --bridge'.
# Idempotent installer + launcher. First boot installs @openape/chat-bridge
# globally via bun (homebrew-provided); subsequent boots skip the install.
set -euo pipefail
export PATH="/opt/homebrew/bin:$HOME/.bun/bin:$PATH"
if ! command -v openape-chat-bridge >/dev/null 2>&1; then
  bun add -g @openape/chat-bridge
fi
set -a
. "$HOME/.pi/agent/.env"
set +a
exec openape-chat-bridge
`
}

export function buildBridgePlist(homeDir: string): string {
  const startScript = `${homeDir}/Library/Application Support/openape/bridge/start.sh`
  const stdoutLog = `${homeDir}/Library/Logs/openape-chat-bridge.log`
  const stderrLog = `${homeDir}/Library/Logs/openape-chat-bridge.err.log`
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${BRIDGE_PLIST_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${startScript}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${homeDir}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>${stdoutLog}</string>
    <key>StandardErrorPath</key>
    <string>${stderrLog}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>${homeDir}</string>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/bin:/bin</string>
    </dict>
</dict>
</plist>
`
}
