// Helpers for `apes agents spawn --bridge`. The chat-bridge is a daemon
// that runs as the agent user, listens to chat.openape.ai, and forwards
// messages to a local LLM CLI (pi). It needs access to a local litellm
// proxy — set up out-of-band by the spawning user (today: hand-crafted
// at ~/litellm/.env).
//
// As of #236 the daemon is installed as a system-wide LaunchDaemon at
// /Library/LaunchDaemons/eco.hofmann.apes.bridge.<agent>.plist with the
// agent set as <UserName>. That makes it boot without anyone being logged
// in (matters for hidden service accounts in the [200,500) UID range
// which never get a GUI session).

import { existsSync, readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

const PLIST_LABEL_PREFIX = 'eco.hofmann.apes.bridge'

export interface BridgeConfig {
  /** Where the bridge will POST messages — http://host:port/v1 */
  baseUrl: string
  /** Master key for the litellm proxy */
  apiKey: string
}

/**
 * Read defaults from `~/litellm/.env` (the hand-crafted location patrick
 * uses today). Returns null if no file or no key found.
 */
export function readLitellmEnv(envPath: string = join(homedir(), 'litellm', '.env')): { apiKey?: string, baseUrl?: string } | null {
  if (!existsSync(envPath)) return null
  try {
    const text = readFileSync(envPath, 'utf8')
    const out: { apiKey?: string, baseUrl?: string } = {}
    for (const line of text.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const eq = trimmed.indexOf('=')
      if (eq < 0) continue
      const key = trimmed.slice(0, eq).trim()
      const value = trimmed.slice(eq + 1).trim()
      if (key === 'LITELLM_MASTER_KEY' || key === 'LITELLM_API_KEY') out.apiKey = value
      if (key === 'LITELLM_BASE_URL') out.baseUrl = value
    }
    return out
  }
  catch {
    return null
  }
}

/** Resolve config from CLI flags + env defaults. CLI wins. */
export function resolveBridgeConfig(opts: {
  cliKey?: string
  cliBaseUrl?: string
  envPath?: string
}): BridgeConfig {
  const env = readLitellmEnv(opts.envPath)
  const apiKey = opts.cliKey ?? env?.apiKey
  const baseUrl = opts.cliBaseUrl ?? env?.baseUrl ?? 'http://127.0.0.1:4000/v1'
  if (!apiKey) {
    throw new Error(
      'No LITELLM_API_KEY resolved. Pass --bridge-key sk-… or write LITELLM_MASTER_KEY into ~/litellm/.env first.',
    )
  }
  return { baseUrl, apiKey }
}

export function bridgePlistLabel(agentName: string): string {
  return `${PLIST_LABEL_PREFIX}.${agentName}`
}

/** Path of the system LaunchDaemon plist. Root-owned, writable only by root. */
export function bridgePlistPath(agentName: string): string {
  return `/Library/LaunchDaemons/${bridgePlistLabel(agentName)}.plist`
}

export function buildBridgeEnvFile(cfg: BridgeConfig): string {
  return `# Auto-generated by 'apes agents spawn --bridge'.
# Read by the chat-bridge daemon at boot to talk to the local LLM proxy.
LITELLM_BASE_URL=${cfg.baseUrl}
LITELLM_API_KEY=${cfg.apiKey}
`
}

/**
 * start.sh content. Slim — assumes the bridge stack (chat-bridge + apes
 * + pi) was already bun-installed during spawn. Each launchd boot only:
 *
 *   1. Drops the litellm pi extension if missing (idempotent).
 *   2. Sources the proxy env + execs the bridge.
 *
 * Boot time goes from ~75s (with installs) to ~3-5s.
 *
 * Token refresh: handled in-process by `@openape/cli-auth`, which
 * does its own Ed25519 challenge-response when the cached IdP token
 * expires (`auth.json.key_path` points at `~/.ssh/id_ed25519`). No
 * `apes login` shell-out needed at boot — the daemon stays connected
 * across the 1h expiry boundary instead of crash-restarting. See #259.
 *
 * To upgrade an agent's bridge after a new release:
 *   apes run --as <name> -- bun update -g @openape/chat-bridge
 */
export function buildBridgeStartScript(): string {
  return `#!/usr/bin/env bash
# Auto-generated by 'apes agents spawn --bridge'.
# Slim launcher — install stack lives in spawn, not here.
set -euo pipefail

export PATH="$HOME/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

# Token refresh is in-process via @openape/cli-auth's challenge-response
# path (auth.json.key_path -> ~/.ssh/id_ed25519). No "apes login" needed
# at boot — keeping start.sh slim avoids the rate-limit dance the old
# refresh hit when KeepAlive crash-restarted the daemon every 1h.

EXT_DIR="$HOME/.pi/agent/extensions"
mkdir -p "$EXT_DIR"
if [ ! -f "$EXT_DIR/litellm.ts" ]; then
  cat > "$EXT_DIR/litellm.ts" <<'PI_EXT_EOF'
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const BASE_URL = process.env.LITELLM_BASE_URL ?? "http://127.0.0.1:4000/v1";

export default async function (pi: ExtensionAPI) {
  pi.registerProvider("litellm", {
    baseUrl: BASE_URL,
    apiKey: "LITELLM_API_KEY",
    api: "openai-completions",
    models: [
      {
        id: "gpt-5.4",
        name: "ChatGPT 5.4 (Subscription)",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: 8192,
      },
      {
        id: "gpt-5.3-codex",
        name: "ChatGPT 5.3 Codex (Subscription)",
        reasoning: false,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: 8192,
      },
    ],
  });
}
PI_EXT_EOF
fi

set -a
. "$HOME/.pi/agent/.env"
set +a
exec openape-chat-bridge
`
}

/**
 * System LaunchDaemon plist. Lives at /Library/LaunchDaemons/. macOS boots
 * it automatically and respawns on crash via KeepAlive. UserName ensures
 * launchd starts the process as the agent (not root), even though the
 * plist itself is root-owned.
 *
 * `OPENAPE_OWNER_EMAIL` is stamped into the daemon environment as a
 * defense-in-depth fallback for the chat-bridge identity check: the
 * canonical source is `owner_email` in `~/.config/apes/auth.json`
 * (written by spawn), but if a future `apes login` ever clobbers that
 * field the bridge can still resolve its owner from this env var.
 */
export function buildBridgePlist(agentName: string, homeDir: string, ownerEmail: string): string {
  const startScript = `${homeDir}/Library/Application Support/openape/bridge/start.sh`
  const stdoutLog = `${homeDir}/Library/Logs/openape-chat-bridge.log`
  const stderrLog = `${homeDir}/Library/Logs/openape-chat-bridge.err.log`
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${bridgePlistLabel(agentName)}</string>
    <key>UserName</key>
    <string>${agentName}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${startScript}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${homeDir}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>${stdoutLog}</string>
    <key>StandardErrorPath</key>
    <string>${stderrLog}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>${homeDir}</string>
        <key>PATH</key>
        <string>${homeDir}/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
        <key>OPENAPE_OWNER_EMAIL</key>
        <string>${ownerEmail}</string>
    </dict>
</dict>
</plist>
`
}
