import { existsSync, copyFileSync, writeFileSync } from 'node:fs'
import { randomBytes } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'
import { defineCommand } from 'citty'
import consola from 'consola'

const DEFAULT_IDP_URL = 'https://id.openape.at'

async function downloadTemplate(repo: string, targetDir: string) {
  const { downloadTemplate: gigetDownload } = await import('giget')
  await gigetDownload(`gh:${repo}`, { dir: targetDir, force: false })
}

function installDeps(dir: string) {
  const hasLockFile = (name: string) => existsSync(join(dir, name))

  if (hasLockFile('pnpm-lock.yaml')) {
    execFileSync('pnpm', ['install'], { cwd: dir, stdio: 'inherit' })
  }
  else if (hasLockFile('bun.lockb')) {
    execFileSync('bun', ['install'], { cwd: dir, stdio: 'inherit' })
  }
  else {
    execFileSync('npm', ['install'], { cwd: dir, stdio: 'inherit' })
  }
}

async function promptChoice(message: string, choices: string[]): Promise<string> {
  const result = await consola.prompt(message, { type: 'select', options: choices })
  if (typeof result === 'symbol') {
    process.exit(0)
  }
  return result as string
}

async function promptText(message: string, defaultValue?: string): Promise<string> {
  const result = await consola.prompt(message, { type: 'text', default: defaultValue, placeholder: defaultValue })
  if (typeof result === 'symbol') {
    process.exit(0)
  }
  return (result as string) || defaultValue || ''
}

export const initCommand = defineCommand({
  meta: {
    name: 'init',
    description: 'Scaffold a new OpenApe project',
  },
  args: {
    sp: {
      type: 'boolean',
      description: 'Create a Service Provider app',
    },
    idp: {
      type: 'boolean',
      description: 'Create an Identity Provider app',
    },
    dir: {
      type: 'positional',
      description: 'Target directory',
      required: false,
    },
  },
  async run({ args }) {
    let mode: 'sp' | 'idp'

    if (args.sp) {
      mode = 'sp'
    }
    else if (args.idp) {
      mode = 'idp'
    }
    else {
      const choice = await promptChoice('What do you want to set up?', [
        'SP — Add login to my app',
        'IdP — Run my own Identity Provider',
      ])
      mode = choice.startsWith('SP') ? 'sp' : 'idp'
    }

    if (mode === 'sp') {
      await initSP(args.dir)
    }
    else {
      await initIdP(args.dir)
    }
  },
})

async function initSP(targetDir?: string) {
  const dir = targetDir || 'my-app'

  if (existsSync(join(dir, 'package.json'))) {
    consola.error(`Directory "${dir}" already contains a project.`)
    return process.exit(1)
  }

  consola.start('Scaffolding SP starter...')
  await downloadTemplate('openape-ai/openape-sp-starter', dir)
  consola.success('Scaffolded from openape-sp-starter')

  consola.start('Installing dependencies...')
  installDeps(dir)
  consola.success('Dependencies installed')

  // Create .env from .env.example
  const envExample = join(dir, '.env.example')
  const envFile = join(dir, '.env')
  if (existsSync(envExample) && !existsSync(envFile)) {
    copyFileSync(envExample, envFile)
    consola.success(`\`.env\` created (using Free IdP at ${DEFAULT_IDP_URL})`)
  }

  console.log('')
  consola.box([
    `cd ${dir}`,
    'npm run dev',
    '',
    'Then open http://localhost:3001/login',
  ].join('\n'))
}

async function initIdP(targetDir?: string) {
  const dir = targetDir || 'my-idp'

  if (existsSync(join(dir, 'package.json'))) {
    consola.error(`Directory "${dir}" already contains a project.`)
    return process.exit(1)
  }

  // Interactive questions
  const domain = await promptText('Domain for the IdP', 'localhost')
  const storage = await promptChoice('Storage backend', [
    'memory (dev only, data lost on restart)',
    'fs (local filesystem)',
    's3 (S3-compatible)',
  ])
  const adminEmail = await promptText('Admin email')

  consola.start('Scaffolding IdP starter...')
  await downloadTemplate('openape-ai/openape-idp-starter', dir)
  consola.success('Scaffolded from openape-idp-starter')

  consola.start('Installing dependencies...')
  installDeps(dir)
  consola.success('Dependencies installed')

  // Generate secrets
  const sessionSecret = randomBytes(32).toString('hex')
  const managementToken = randomBytes(32).toString('hex')
  consola.success('Secrets generated')

  // Determine origin/issuer
  const isLocalhost = domain === 'localhost'
  const origin = isLocalhost ? 'http://localhost:3000' : `https://${domain}`

  // Write .env
  const envContent = [
    '# Generated by apes init --idp',
    '',
    `NUXT_OPENAPE_SESSION_SECRET=${sessionSecret}`,
    `NUXT_OPENAPE_ADMIN_EMAILS=${adminEmail}`,
    `NUXT_OPENAPE_MANAGEMENT_TOKEN=${managementToken}`,
    `NUXT_OPENAPE_ISSUER=${origin}`,
    `NUXT_OPENAPE_RP_NAME=My Identity Provider`,
    `NUXT_OPENAPE_RP_ID=${domain}`,
    `NUXT_OPENAPE_RP_ORIGIN=${origin}`,
  ].join('\n')

  writeFileSync(join(dir, '.env'), envContent + '\n', { mode: 0o600 })
  consola.success('.env created')

  console.log('')
  consola.box([
    `cd ${dir}`,
    'npm run dev',
    '',
    'Then open http://localhost:3000/admin',
    '',
    ...(isLocalhost
      ? []
      : [
          'For production:',
          `  1. DNS TXT Record: _ddisa.${domain.replace(/^id\./, '')} → "v=ddisa1 idp=${origin}"`,
          `  2. Storage: switch to ${storage.includes('s3') ? 's3' : 'fs'} in nuxt.config.ts`,
          '  3. Deploy: vercel deploy',
        ]),
  ].join('\n'))
}
