// Per-agent pm2 supervisor — Model C of Phase E.
//
// Each agent runs ITS OWN pm2-god daemon as the agent's macOS uid.
// The bridge process is then a direct child of agentx's pm2 (no
// `apes run --as` indirection in the process tree). Each agent's
// `~/.pm2/` is independent: own logs, own restart-history, own crash
// domain. `pm2 list` from agentx's shell shows only that agent's
// processes — clean per-agent operations.
//
// The Nest itself runs as `_openape_nest` and shell-outs to
// `apes run --as <agent> --wait -- pm2 <subcmd>` for every
// management call. escapes-helper's setuid switch puts the pm2
// invocation in the agent's identity; pm2 spawned that way persists
// in the agent's home, and subsequent `pm2 start` calls reattach to
// the same god daemon.
//
// Reconcile semantics (idempotent):
//   - For each registered agent with bridge != null:
//       write /var/openape/nest/agents/<name>/ecosystem.config.js
//       run `apes run --as <name> --wait -- pm2 startOrReload <path>`
//   - For each agent in the registry that's gone:
//       run `apes run --as <name> --wait -- pm2 delete <pm2-name>`
//
// We don't try to talk to per-agent pm2-daemons via JSON RPC from
// here — each runs in a different uid sandbox. Shell-outs through
// apes-run are the only sane channel.

import { execFile } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { promisify } from 'node:util'
import type { AgentEntry } from './registry'

const execFileAsync = promisify(execFile)
// World-readable so agents can read their own ecosystem.config.js
// when pm2 (running as the agent uid) opens the file. The Nest's
// own private state stays under /var/openape/nest/ at mode 750;
// these per-agent ecosystem files are mechanically generated and
// hold no secrets, so 755 dir + 644 file is fine.
const AGENTS_DIR = '/var/openape/agents'

export interface Pm2SupervisorDeps {
  apesBin: string
  log: (line: string) => void
}

function pm2AppName(agentName: string): string {
  return `openape-bridge-${agentName}`
}

function ecosystemPath(agentName: string): string {
  return join(AGENTS_DIR, agentName, 'ecosystem.config.js')
}

function ecosystemContents(apesBin: string, agentName: string): string {
  void apesBin
  return `// Auto-generated by Pm2Supervisor for agent '${agentName}'.
// Edit at runtime via:
//   apes run --as ${agentName} -- pm2 reload ${pm2AppName(agentName)}
module.exports = {
  apps: [{
    name: '${pm2AppName(agentName)}',
    script: 'openape-chat-bridge',
    autorestart: true,
    max_restarts: 10,
    min_uptime: '30s',
    restart_delay: 2000,
    merge_logs: true,
  }],
}
`
}

function startScriptPath(agentName: string): string {
  return join(AGENTS_DIR, agentName, 'start.sh')
}

/**
 * Per-agent wrapper script that the supervisor invokes via
 * `apes run --as <agent> -- bash <path>`. The script:
 *   - sets HOME explicitly to the agent's home (escapes-helper
 *     does setuid but doesn't always reset HOME — pm2 then writes
 *     ~/.pm2 to the wrong dir without this)
 *   - sets PM2_HOME to make pm2's location explicit
 *   - redirects stdio to a per-agent log + /dev/null so pm2's
 *     god-daemon detach doesn't keep the parent's pipes open
 *     (which causes the parent's execFile to block on the
 *     timeout instead of returning when pm2 cli exits)
 *   - calls pm2 startOrReload with the ecosystem path
 */
function startScriptContents(agentName: string): string {
  const ecosystem = ecosystemPath(agentName)
  const log = `/var/log/openape/${agentName}-pm2.log`
  return `#!/bin/bash
# Auto-generated by Pm2Supervisor for agent '${agentName}'.
set -e
export HOME="$(dscl . -read /Users/${agentName} NFSHomeDirectory 2>/dev/null | awk '{print $2}')"
test -n "$HOME" || { echo "no NFSHomeDirectory for ${agentName}" >&2; exit 1; }
export PM2_HOME="$HOME/.pm2"
mkdir -p "$(dirname "${log}")"
exec pm2 startOrReload ${ecosystem} >> ${log} 2>&1 < /dev/null
`
}

export class Pm2Supervisor {
  private inflight = new Set<string>()

  constructor(private deps: Pm2SupervisorDeps) {}

  /** Bring per-agent pm2 state in line with the registry. Idempotent. */
  async reconcile(desired: AgentEntry[]): Promise<void> {
    for (const agent of desired) {
      if (agent.bridge == null) continue
      if (this.inflight.has(agent.name)) continue
      this.inflight.add(agent.name)
      try { await this.startOrReload(agent.name) }
      catch (err) {
        this.deps.log(`pm2-supervisor: ${agent.name} reconcile errored: ${err instanceof Error ? err.message.split('\n')[0] : String(err)}`)
      }
      finally { this.inflight.delete(agent.name) }
    }
  }

  /** Stop one agent's pm2 app — used at destroy time. */
  async stop(agentName: string): Promise<void> {
    const name = pm2AppName(agentName)
    try {
      await this.runAsAgent(agentName, ['pm2', 'delete', name])
      this.deps.log(`pm2-supervisor: deleted ${name}`)
    }
    catch (err) {
      // pm2 returns non-zero if the app doesn't exist — fine.
      this.deps.log(`pm2-supervisor: delete ${name}: ${err instanceof Error ? err.message.split('\n')[0] : String(err)}`)
    }
  }

  /** Best-effort cleanup — called on Nest shutdown. We don't kill
   *  the per-agent pm2-daemons; they should keep running so bridges
   *  stay alive across Nest restarts. No-op for now. */
  async stopAll(): Promise<void> {
    /* deliberately empty — per-agent pm2 outlives the Nest */
  }

  private async startOrReload(agentName: string): Promise<void> {
    // Materialise the ecosystem file under /var/openape/nest/agents/
    // (the Nest's data dir, owned by _openape_nest). The agent's pm2
    // reads it via apes-run+escapes — escapes inherits ENV but the
    // working dir flips to the agent's $HOME, so we use the absolute
    // path.
    // Ensure the parent + per-agent dirs are world-traversable so
    // agents (different uids) can read their own ecosystem.config.js.
    mkdirSync(AGENTS_DIR, { recursive: true, mode: 0o755 })
    const dir = join(AGENTS_DIR, agentName)
    mkdirSync(dir, { recursive: true, mode: 0o755 })
    const path = ecosystemPath(agentName)
    writeFileSync(path, ecosystemContents(this.deps.apesBin, agentName), { mode: 0o644 })

    // Drop the per-agent start.sh next to the ecosystem file. Going
    // through a script (not a `bash -c "..."` one-liner) sidesteps
    // arg-quoting issues with escapes-helper, which receives the
    // command as separate argv elements and bash -c then collapses
    // anything past the script-string into positional args
    // ($0, $1, ...) — silently dropping the redirects we expected.
    const startPath = startScriptPath(agentName)
    writeFileSync(startPath, startScriptContents(agentName), { mode: 0o755 })
    void path

    // Run start.sh — pm2 startOrReload's exit code is unreliable
    // (it returns non-zero in some "already running, reloaded" paths
    // even when the work succeeded). We tolerate the non-zero, then
    // probe `pm2 jlist` for the expected app to confirm. The agent
    // log file (/var/log/openape/<agent>-pm2.log) carries the full
    // pm2 output for post-mortem if the probe fails.
    try { await this.runAsAgent(agentName, ['bash', startPath]) }
    catch { /* pm2 exit-code noise — verify via jlist below */ }

    let online = false
    try {
      const { stdout } = await this.runAsAgent(agentName, ['pm2', 'jlist'])
      const json = stdout.match(/\[\s*\{.*\}\s*\]/s)?.[0]
      if (json) {
        const list = JSON.parse(json) as Array<{ name?: string, pm2_env?: { status?: string } }>
        online = list.some(p => p.name === pm2AppName(agentName) && p.pm2_env?.status === 'online')
      }
    }
    catch { /* probe failure → log generic error below */ }

    if (online) {
      this.deps.log(`pm2-supervisor: ${agentName} bridge online (pm2)`)
    }
    else {
      this.deps.log(`pm2-supervisor: ${agentName} bridge NOT online — see /var/log/openape/${agentName}-pm2.log`)
    }
  }

  /** Run a pm2 subcommand AS the agent — escapes-helper does the
   *  setuid switch, then exec's pm2 in the agent's uid.
   *
   *  cwd: the agent process inherits cwd from the spawning Nest
   *  daemon, whose cwd is /var/openape/nest (mode 750, no access for
   *  other uids). Without setting cwd to a world-readable dir, the
   *  child's first `process.cwd()` call (which Node does internally
   *  during module loading) throws EACCES. /tmp is the most portable
   *  always-writable location.
   */
  private async runAsAgent(agentName: string, args: string[]): Promise<{ stdout: string, stderr: string }> {
    try {
      return await execFileAsync(
        this.deps.apesBin,
        ['run', '--as', agentName, '--wait', '--', ...args],
        { maxBuffer: 1024 * 1024, env: process.env, timeout: 60_000, cwd: '/tmp' },
      )
    }
    catch (err) {
      // Surface stderr in the error message — the bare execFile
      // error only says "Command failed" without telling us why.
      const e = err as { stderr?: string, stdout?: string, message?: string }
      const detail = (e.stderr ?? '').trim().split('\n').slice(-3).join(' / ')
      const stdoutDetail = (e.stdout ?? '').trim().split('\n').slice(-2).join(' / ')
      throw new Error(`${e.message?.split('\n')[0] ?? 'execFile failed'} | stderr: ${detail || '<empty>'} | stdout: ${stdoutDetail || '<empty>'}`)
    }
  }
}
