// Per-agent pm2 supervisor — Model C of Phase E.
//
// Each agent runs ITS OWN pm2-god daemon as the agent's macOS uid.
// The bridge process is then a direct child of agentx's pm2 (no
// `apes run --as` indirection in the process tree). Each agent's
// `~/.pm2/` is independent: own logs, own restart-history, own crash
// domain. `pm2 list` from agentx's shell shows only that agent's
// processes — clean per-agent operations.
//
// The Nest itself runs as `_openape_nest` and shell-outs to
// `apes run --as <agent> --wait -- pm2 <subcmd>` for every
// management call. escapes-helper's setuid switch puts the pm2
// invocation in the agent's identity; pm2 spawned that way persists
// in the agent's home, and subsequent `pm2 start` calls reattach to
// the same god daemon.
//
// Reconcile semantics (idempotent):
//   - For each registered agent with bridge != null:
//       write /var/openape/nest/agents/<name>/ecosystem.config.js
//       run `apes run --as <name> --wait -- pm2 startOrReload <path>`
//   - For each agent in the registry that's gone:
//       run `apes run --as <name> --wait -- pm2 delete <pm2-name>`
//
// We don't try to talk to per-agent pm2-daemons via JSON RPC from
// here — each runs in a different uid sandbox. Shell-outs through
// apes-run are the only sane channel.

import { execFile } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { promisify } from 'node:util'
import type { AgentEntry } from './registry'

const execFileAsync = promisify(execFile)
// World-readable so agents can read their own ecosystem.config.js
// when pm2 (running as the agent uid) opens the file. The Nest's
// own private state stays under /var/openape/nest/ at mode 750;
// these per-agent ecosystem files are mechanically generated and
// hold no secrets, so 755 dir + 644 file is fine.
const AGENTS_DIR = '/var/openape/agents'

export interface Pm2SupervisorDeps {
  apesBin: string
  log: (line: string) => void
}

function pm2AppName(agentName: string): string {
  return `openape-bridge-${agentName}`
}

function ecosystemPath(agentName: string): string {
  return join(AGENTS_DIR, agentName, 'ecosystem.config.js')
}

function ecosystemContents(apesBin: string, agentName: string): string {
  // Bridge invocation: agentx's pm2 will spawn `openape-chat-bridge`
  // directly (no `apes run --as` wrapper — pm2 already runs as
  // agentx). The bridge auto-loads ~/Library/Application Support/
  // openape/bridge/.env at boot for LITELLM_*+APE_CHAT_BRIDGE_MODEL.
  void apesBin
  return `// Auto-generated by Pm2Supervisor for agent '${agentName}'.
// Edit at runtime via:
//   apes run --as ${agentName} -- pm2 reload ${pm2AppName(agentName)}
module.exports = {
  apps: [{
    name: '${pm2AppName(agentName)}',
    script: 'openape-chat-bridge',
    autorestart: true,
    max_restarts: 10,
    min_uptime: '30s',
    restart_delay: 2000,
    merge_logs: true,
  }],
}
`
}

export class Pm2Supervisor {
  private inflight = new Set<string>()

  constructor(private deps: Pm2SupervisorDeps) {}

  /** Bring per-agent pm2 state in line with the registry. Idempotent. */
  async reconcile(desired: AgentEntry[]): Promise<void> {
    for (const agent of desired) {
      if (agent.bridge == null) continue
      if (this.inflight.has(agent.name)) continue
      this.inflight.add(agent.name)
      try { await this.startOrReload(agent.name) }
      catch (err) {
        this.deps.log(`pm2-supervisor: ${agent.name} startOrReload failed: ${err instanceof Error ? err.message.split('\n')[0] : String(err)}`)
      }
      finally { this.inflight.delete(agent.name) }
    }
  }

  /** Stop one agent's pm2 app — used at destroy time. */
  async stop(agentName: string): Promise<void> {
    const name = pm2AppName(agentName)
    try {
      await this.runAsAgent(agentName, ['pm2', 'delete', name])
      this.deps.log(`pm2-supervisor: deleted ${name}`)
    }
    catch (err) {
      // pm2 returns non-zero if the app doesn't exist — fine.
      this.deps.log(`pm2-supervisor: delete ${name}: ${err instanceof Error ? err.message.split('\n')[0] : String(err)}`)
    }
  }

  /** Best-effort cleanup — called on Nest shutdown. We don't kill
   *  the per-agent pm2-daemons; they should keep running so bridges
   *  stay alive across Nest restarts. No-op for now. */
  async stopAll(): Promise<void> {
    /* deliberately empty — per-agent pm2 outlives the Nest */
  }

  private async startOrReload(agentName: string): Promise<void> {
    // Materialise the ecosystem file under /var/openape/nest/agents/
    // (the Nest's data dir, owned by _openape_nest). The agent's pm2
    // reads it via apes-run+escapes — escapes inherits ENV but the
    // working dir flips to the agent's $HOME, so we use the absolute
    // path.
    // Ensure the parent + per-agent dirs are world-traversable so
    // agents (different uids) can read their own ecosystem.config.js.
    mkdirSync(AGENTS_DIR, { recursive: true, mode: 0o755 })
    const dir = join(AGENTS_DIR, agentName)
    mkdirSync(dir, { recursive: true, mode: 0o755 })
    const path = ecosystemPath(agentName)
    writeFileSync(path, ecosystemContents(this.deps.apesBin, agentName), { mode: 0o644 })

    // pm2 startOrReload is the idempotent operation: starts if not
    // there, reloads (zero-downtime restart) if already there.
    await this.runAsAgent(agentName, ['pm2', 'startOrReload', path])
    this.deps.log(`pm2-supervisor: ${agentName} bridge (re)started via pm2`)
  }

  /** Run a pm2 subcommand AS the agent — escapes-helper does the
   *  setuid switch, then exec's pm2 in the agent's uid. */
  private async runAsAgent(agentName: string, args: string[]): Promise<{ stdout: string }> {
    return execFileAsync(
      this.deps.apesBin,
      ['run', '--as', agentName, '--wait', '--', ...args],
      { maxBuffer: 1024 * 1024, env: process.env, timeout: 60_000 },
    )
  }
}
