#!/usr/bin/env node
// Deterministic Mermaid graph of the INTERNAL (@openape/* workspace) dependency
// structure — the architecture view, regenerated from code so it can't drift.
//   pnpm graph   → writes docs/architecture/dependency-graph.md
// No graphviz needed: Mermaid renders inline on Forgejo/GitHub.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const LAYERS = ['packages', 'modules', 'apps']

const pkgs = []
for (const layer of LAYERS) {
  for (const entry of readdirSync(join(root, layer), { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    try {
      const json = JSON.parse(readFileSync(join(root, layer, entry.name, 'package.json'), 'utf8'))
      if (json.name) pkgs.push({ layer, name: json.name, deps: { ...json.dependencies, ...json.devDependencies } })
    }
    catch {}
  }
}
pkgs.sort((a, b) => a.name.localeCompare(b.name))

const names = new Set(pkgs.map(p => p.name))
const id = n => n.replace(/[^a-z0-9]/gi, '_')

const lines = ['graph LR']
for (const layer of LAYERS) {
  const inLayer = pkgs.filter(p => p.layer === layer)
  if (!inLayer.length) continue
  lines.push(`  subgraph ${layer}`)
  for (const p of inLayer) lines.push(`    ${id(p.name)}["${p.name}"]`)
  lines.push('  end')
}
let edgeCount = 0
for (const p of pkgs) {
  for (const dep of Object.keys(p.deps).sort()) {
    if (names.has(dep) && dep !== p.name) {
      lines.push(`  ${id(p.name)} --> ${id(dep)}`)
      edgeCount++
    }
  }
}

const out = `# Internal dependency graph

> Generated by \`pnpm graph\` (\`scripts/dependency-graph.mjs\`) — do not edit by hand.
> Shows the \`@openape/*\` workspace dependencies between packages, modules and apps.

\`\`\`mermaid
${lines.join('\n')}
\`\`\`
`
mkdirSync(join(root, 'docs/architecture'), { recursive: true })
writeFileSync(join(root, 'docs/architecture/dependency-graph.md'), out)
console.log(`dependency-graph.md — ${pkgs.length} packages, ${edgeCount} internal edges`)
