#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { root, workspaces } from './check.mjs'

const packages = workspaces()
const purposes = JSON.parse(readFileSync(join(root, '.openape/workspace-purpose.json'), 'utf8'))
const names = new Set(packages.map(p => p.name))
for (const p of packages) {
  if (!purposes[p.path]) throw new Error(`Missing workspace purpose: ${p.path}`)
}
for (const path of Object.keys(purposes)) {
  if (!packages.some(p => p.path === path)) throw new Error(`Obsolete workspace purpose: ${path}`)
}
const escape = text => String(text).replaceAll('|', '\\|').replaceAll('\n', ' ')
const scripts = ['dev', 'start', 'build', 'lint', 'typecheck', 'test', 'test:e2e', 'test:layout']
const map = `# Workspace map

Generated by \`pnpm graph\` from workspace manifests and
\`.openape/workspace-purpose.json\`. Validate with \`pnpm docs:check\`.
${packages.length} workspaces; package names, not folder guesses, are pnpm filters.

| Workspace | Path | Purpose | Available scripts |
|---|---|---|---|
${packages.map(p => `| \`${p.name}\` | [${p.path}](../../${p.path}) | ${escape(purposes[p.path])} | ${scripts.filter(s => p.scripts[s]).map(s => `\`${s}\``).join(', ')} |`).join('\n')}

Use \`pnpm --filter <workspace-name> <script>\`. Scripts absent from the table
are not checks. The shared contract records the existing coverage exceptions.
Application configuration and fixtures are documented in [local development](../operations/local-development.md).
`
const ids = new Map(packages.map((p, i) => [p.name, `w${i}`]))
const graph = ['graph LR']
for (const layer of ['packages', 'modules', 'apps', 'examples']) {
  graph.push(`  subgraph ${layer}`)
  for (const p of packages.filter(p => p.path.startsWith(`${layer}/`))) graph.push(`    ${ids.get(p.name)}["${p.name}"]`)
  graph.push('  end')
}
for (const p of packages) {
  for (const dependency of Object.keys(p.deps).filter(n => names.has(n) && n !== p.name).sort()) graph.push(`  ${ids.get(p.name)} --> ${ids.get(dependency)}`)
}
const artifacts = {
  'workspace-map.md': map,
  'dependency-graph.md': `# Internal dependency graph\n\nGenerated by \`pnpm graph\`; validate with \`pnpm docs:check\`.\nIncludes packages, modules, apps and examples. Arrows point to dependencies.\n\n\`\`\`mermaid\n${graph.join('\n')}\n\`\`\`\n`,
}
const check = process.argv.includes('--check')
for (const [name, content] of Object.entries(artifacts)) {
  const path = join(root, 'docs/architecture', name)
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) throw new Error(`${name} is stale; run pnpm graph and commit both generated documents.`)
  }
  else { mkdirSync(join(root, 'docs/architecture'), { recursive: true }); writeFileSync(path, content) }
}
console.log(`${check ? 'Verified' : 'Generated'} workspace map and graph: ${packages.length} workspaces`)
