export type { ProofCliDescriptor } from './descriptor'
export { createProofClient } from './client'
export { emitAttentionEvents, lifecycleEvent, proofAttachedEvent, ulid, verdictRequestedEvents } from './attention'
export type { AttentionActor, VerdictBriefing } from './attention'
export { makeLoginCommand } from './commands/login'
export { makeLogoutCommand } from './commands/logout'
export { makeWhoamiCommand } from './commands/whoami'
export { makeDocsCommand } from './commands/docs'
export { runProofCli } from './run'
export { error, fmtTime, info, printJson, printLine, printNdjson } from './output'
export type { OutputOptions } from './output'
